accept exchange feed options in config
bmoscon/cryptostore pull request #190
Opened 2021-07-24 03:13 UTC by jinusean

### Description of code - what bug does this fix / what feature does this add?

- [x] - Tested
- [x] - Changelog updated

Relevant update to cryptofeed's changes in https://github.com/bmoscon/cryptofeed/pull/574

2021-07-24 16:37 UTC, bmoscon commented on config.yaml
> +storage: [artic, influx]
arctic is spelled incorrectly here

2021-07-24 16:37 UTC, bmoscon commented on config.yaml
>      COINGECKO:
just remove the whole coingecko block

2021-07-24 16:39 UTC, bmoscon requested changes
see other comments

2021-07-25 02:25 UTC, jinusean commented on config.yaml
>      COINGECKO:
Removed

2021-07-25 02:25 UTC, jinusean commented on config.yaml
> +storage: [artic, influx]
Spelling fixed.

2021-07-25 02:26 UTC, jinusean commented
Requested changes have been applied.

2021-07-27 12:58 UTC, bmoscon approved these changes

2021-07-27 12:58 UTC, merged